# Auto Assign Configuration
addReviewers: true
reviewers:
  - "purvanshjoshi"
addAssignees: true
assignees:
  - "purvanshjoshi"
numberOfReviewers: 1
numberOfAssignees: 1
skipKeywords:
  - "WIP"
  - "Draft"
