version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule: 
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "area:backend"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
