area:backend:
  - changed-files:
    - any-glob-to-any-file: ['backend/**/*']

area:extension:
  - changed-files:
    - any-glob-to-any-file: ['extension/**/*']

area:docs:
  - changed-files:
    - any-glob-to-any-file: ['*.md', 'docs/**/*']

area:github:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*']
