name: "Checkstyle Guard"

on:
  pull_request:
    paths:
      - '**.java'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Run Checkstyle'
        uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          checkstyle_config: checkstyle.xml
          level: warning
